### DISCUSSION TITLE
The OCL in yaml?

### DISCUSSION THREAD

**Discussion by iskey** [eclipse-xpanse/xpanse#113] [Ideas]
I propose refactoring the OCL in YAML format. As follows:

```yaml
resources:
  - kind: vpc
    name: vpc1
    properties:
      cidr: 192.168.0.0/16
  - kind: subnet
    name: subnet-web
    properties:
      cidr: 192.168.10.0/24
      gatewayIp: 192.168.10.1
      vpc: vpc1
  - kind: security
    name: osc-res-sg
    properties:
      rules:
        - name: osc-res-sg-kafka
          priority: 1
          protocol: tcp
          cidr: 10.10.2.6/32,
          direction: inbound,
          ports: 8080, 9092-9093, 2181
          action: allow
        - name: osc-res-sg-ssh-public
          priority: 1
          protocol: tcp
          cidr: 121.36.59.153/32
          direction: inbound
          ports: 22, 8080, 9092-9093,2181
          action: allow
        - name: osc-res-sg-ssh-private
          priority: 1,
          protocol: tcp,
          cidr: 198.19.0.0/16
          direction: inbound
          ports: 22
          action: allow
  - kind: storage
    name: osc-res-storage
    properties:
      type: SAS
      size: 20GiB
  - kind: vm
    name: kafka-vm
    properties:
      type: c7.large.4
      subnet: subnet-web
      provisioner: kafka
      security: osc-res-sg
      storage: osc-res-storage
      publicly: true
  - kind: baseImage
    name: Ubuntu 20.04 server 64bit
    properties:
      type: t2.large
      filters:
        name: ubuntu-for-osc-*
  - kind: baseImage
    name: centos-x64
    properties:
      type: t2.large
  - kind: provisioner
    name: my-kafka-release
    properties:
      baseImage: Ubuntu 20.04 server 64bit
  - kind: billing
    name:
    properties:
      model: flat
      period: monthly
      currency: euro
      fixedPrice: 20
      variablePrice: 10
      variableItem: instance
```

**Comment by jbonofre** [comment]
No problem for me, and it's pretty easy: just add yaml databind on the ocl-loader and it works :)

**Comment by iskey** [comment]
Hi @jbonofre, My idea is to pack all kinds of  `OCL` object to one object like this:
```
category:  xxx
    name: yyy
    properties:
       aaa: bbb
       ccc: ddd
```
and the reference can be done with `category` + `name` pairs.
