### ISSUE TITLE
extend OCL with AZ information

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1439]
Currently the user can select region while choosing a service. It should also be possible to chose the AZ for some services.

- [ ]  AvailabilityZoneConfig =  displayName: string, varName: string
- [ ]  ServiceAvailability - List<AvailabilityZoneConfig>
- [ ] Add OCL with new optional field `serviceAvailability` to `Deployment` object. If provided atleast one entry must be provided in the list.
- [ ] Add optional `availabilityZone` field to DeployRequest -> <String, String> (varName, varValue)
- [ ] Forward availability zone request value to deployer if the value is present. -> Similar to how flavor properties are implemented.
- [ ] Update service template swagger generation.
- [ ] Update samples.

Ocl should like below -

```yaml
 deployment:
    serviceAvailability:
      - displayName: Primary AZ
        varName: primary_az
      - displayName: Secondary AZ
        varName: secondary_az
```
