### ISSUE TITLE
update OCL to support service specification modifications

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1448]
- [ ] Create new type `ModificationImpact`
- [ ] Add `ModificationImpact` to flavors as mandatory variable
- [ ] Add `ModificationImpact` to each DeployVariable as mandatory variable.
- [ ] No logic in the deployer based on these values. These are only for clients. 

```yaml
modificationImpact:
    isDataLost: boolean
   isServiceInterrupted: boolean
```
