### ISSUE TITLE
Add pricing information to each flavor

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1544]
- [ ] Create PricingPeriod enum with values `yearly`, `monthly`, `daily`, `oneTime`
- [ ] create new type `Price` type - cost, currency, interval
- [ ] create new `currency` enum - USD, EUR, CNY
- [ ] add `pricing` to each flavor and it must have the following structure. Add models to types wherever necessary.  See comments in the below yaml for more info.
- [ ] To be returned only in ISV and CSP API methods. This must be completely hidden from end user. 

```yaml
flavors:
  serviceFlavors:
    - name: 1-zookeeper-with-3-worker-nodes-normal
      pricing:
        # Ensure one of the resourceUsage or FixedPrice is provided.
        resourceUsage: # Optional
          resources:
            - deployResourceKind: vm #DeployerKind Enum
              count: 3 #integer
              properties: # Map<String, String>
                cloud_service_type: xxx
                resource_type: xxx
                resource_spec: xxx
            - deployResourceKind: volume
              count: 3
              properties: # Map<String, String>
                cloud_service_type: xxx
                resource_type: xxx
                resource_spec: xxx
          markUpPrice: # Optional Price
            cost: 50
            currency: USD
            interval: Monthly
          licensePrice: #Optional Price
            price: 100
            currency: US
            interval: Monthly
        fixedPrice: #Optional Price
          price: 50
          currency: USD
          billingFrequency: Monthly
        isPriceOnlyForManagementLayer: true # mandatory
      properties:
        worker_nodes_count: 3
```

**Comment by Alice1319** [comment]
I'll take this.

**Comment by baixinsui** [comment]
@swaroopar  
> * [ ]  To be returned only in ISV and CSP API methods. This must be completely hidden from end user.
Does this item depend on the condition 'isPriceOnlyForManagementLayer' is true? Otherwise, What is the purpose of this field?
>         isPriceOnlyForManagementLayer: true # mandatory

**Comment by swaroopar** [comment]
@baixinsui `isPriceOnlyForManagementLayer` this flag is to define that the price is only for the management layer of the service. and additional price will incur for the usage of workload nodes. 
This is something for services which  are similar to kubernetes where the price we show is only for the management layer and the customer will incur more charges based on how many workload nodes are used, etc.

**Comment by baixinsui** [comment]
@swaroopar Ok. According to the previously discussed content and the price service of the Huawei Cloud. I add the pricing for the flavors of the service template with name 'huawei-compute-terraform-dev.yml' under the package sample as below:

```
flavors:
  serviceFlavors:
    - name: 2vCPUs-4GB-normal
      # The pricing of the flavor.
      pricing:
        # Used to calculate charges when users select 'pay_per_use' as the billing mode.
        resourceUsage:
          resources:
            - deployResourceKind: vm
              count: 1
              properties:
                cloud_service_type: hws.service.type.ec2
                resource_type: hws.resource.type.vm
                resource_spec: s6.large.2.linux
            - deployResourceKind: volume
              count: 1
              properties:
                cloud_service_type: hws.service.type.ebs
                resource_type: hws.resource.type.volume
                resource_spec: SSD
                resourceSize: 40
            - deployResourceKind: publicIP
              count: 1
              properties:
                cloud_service_type: hws.service.type.vpc
                resource_type: hws.resource.type.bandwidth
                resource_spec: 19_bgp
                resourceSize: 5
          markUpPrice:
            cost: 0.72
            currency: CNY
            period: hourly
          licensePrice:
            cost: 0.80
            currency: CNY
            period: hourly
        # Used to calculate charges when users do not select 'pay_per_use' as the billing mode.
        fixedPrice:
          cost: 300
          currency: CNY
          period: monthly
        isPriceOnlyForManagementLayer: true
      # Properties for the service, which can be used by the deployment.
      properties:
        flavor_id: s6.large.2
```
If there are no problems, I will update the relevant data model according to the current template and fill in the price information of other flavors and other sample templates. Meanwhile, could you please update the relevant description in the issue?
