### ISSUE TITLE
make all fixed prices region specific

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1851]
- [ ] fixedPrice, markupPrice and licensePrice must be made region specific. 
- [ ] Make it a list as below
     
```yaml
       fixedPrice
         - region: eu-west-101
           price:
             cost: 12.20
             currency: EUR
             period: yearly
         - region: any
            price:
              cost: 13.00
              currency: USD
              period: yearly
   ```
- [ ] We must define a special region name `any`. When this provided, prices for all unknown regions are calculated using this configuration.
