### ISSUE TITLE
extend OCL to support configuration management information

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#1866]
- [ ] Add `ServiceConfigurationManage` optional object to OCL. 
- [ ] Create ``ConfigurationManagerTool` Enum with only one value - Ansible. 
- [ ] Add configManageScripts type. - Should be a list. and size of the list must be min 1. 
- [ ] Move configurationParameters field inside `ServiceConfigurationManage`

example
````yaml
serviceConfigurationManage:
  type: ansible #enum
  configManageScripts:
      - configManager: kafka-broker # string. Should be the name available in the deployer script
        runOnlyOnce: false # boolean. Means should the configuration update run on each node of the specific component or just one.
        ansibleScriptConfig:
          playbookName: "kafka-container-manage.yml" #name of the file in the script
          virtualEnv: "" # Path to activate virtualenv
          pythonVersion: 3.11 # version of the python - type float
          isPrepareAnsibleEnvironment: true # boolean The agent will prepare the virtual environment if this true. Otherwise it is assumed that the environment is already prepared as part of the resource creation. 
          repoUrl: https://github.com/swaroopar/osc
          branch: feature/testAnsible
          requirementsFile: 'requirements.txt' # Full path of the requirements file in GIT repo.
          galaxyFile: '' #install roles and collections
          scriptsPath: "samples/ansible" #location of the playbook in repo
          ansibleInventoryRequired: false # boolean. Defines if we need a full inventory request.
      - configManager: zookeeper
        runOnlyOnce: true
        ansibleScriptConfig:
          playbookName: "kafka-container-manage.yml" #name of the file in the script
          virtualEnv: "" # Path to activate virtualenv. will be used by agent to run ansible job.
          pythonVersion: 3.11 # version of the python - type float
          isPrepareAnsibleEnvironment: true # boolean
          repoUrl: https://github.com/swaroopar/osc
          branch: feature/testAnsible
          requirementsFile: 'requirements.txt'
          galaxyFile: '' #install roles
          scriptsPath: [ "location of the playbook in repo" ]
  configurationParameters:
      - name: kafka_cfg_message_max_bytes
        kind: variable
        dataType: number
        description: Parameters used to configure the Kafka server or client to set the maximum number of bytes for Kafka messages.
        initialValue: 1048576
        managedBy: 'kafka-broker'
        modificationImpact:
          isDataLost: true
          isServiceInterrupted: true
        isReadOnly: false
```
