### ISSUE TITLE
extend OCL to support service actions. 

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#2207]
- [ ] Add new element – serviceActions with type  as List<ServiceChangeManage>
- [ ] Action name must be unique within a service template. 
- [ ] Validate changeHandler same like what we did for config manager.

```
serviceActions:
  - name: upgrade
    type: ansible
    actionManageScripts:
      - changeHandler: kafka-broker
        runOnlyOnce: false
        ansibleScriptConfig:
          playbookName: "middleware/ansible/kafka/kafka-container-manage.yml"
          virtualEnv: ""
          pythonVersion: "3.10"
          repoUrl: https://github.com/eclipse-xpanse/xpanse-samples
          branch: main
          requirementsFile: "requirements.txt"
          galaxyFile: ""
          ansibleInventoryRequired: false
    actionParameters:
      - name: kafka_cfg_message_max_bytes
        kind: variable
        dataType: number
        description: Parameters used to configure the Kafka server or client to set the maximum number of bytes for Kafka messages.
        initialValue: 1048576
        managedBy: 'kafka-broker'
        modificationImpact:
          isDataLost: true
          isServiceInterrupted: true
        isReadOnly: false
  - name: backup
    type: ansible
    actionManageScripts:
      - changeHandler: zookeeper
        runOnlyOnce: true
        ansibleScriptConfig:
          playbookName: "middleware/ansible/kafka/kafka-container-manage.yml"
          virtualEnv: ""
          pythonVersion: "3.10"
          repoUrl: https://github.com/eclipse-xpanse/xpanse-samples
          branch: main
          requirementsFile: "requirements.txt"
          galaxyFile: ""
          ansibleInventoryRequired: false
    actionParameters:
      - name: kafka_cfg_message_max_bytes
        kind: variable
        dataType: number
        description: Parameters used to configure the Kafka server or client to set the maximum number of bytes for Kafka messages.
        initialValue: 1048576
        managedBy: 'kafka-broker'
        modificationImpact:
          isDataLost: true
          isServiceInterrupted: true
        isReadOnly: false
```
