### ISSUE TITLE
Enable Oauth2 on Swagger-UI

### ISSUE THREAD

**Issue by swaroopar** [eclipse-xpanse/xpanse#565]
Swagger-UI must have Oauth2 enabled to provider login-ui redirection and execute all further requests with authorization

- [ ] Add configuration to enable authorization on swagger-ui. Below is the sample configuration
- [ ] Ensure the authentication is enabled only when `zitadel` profile is activated. 
- [ ] add a 'web' application on Zitadel for swagger-UI with correct redirect URL
- [ ] Document the application creation process.
- [ ] Provide documentation to override values of clientid, authurl and token url with startup.

```java
@SecurityScheme(name = "security_auth", type = SecuritySchemeType.OAUTH2,
        in = SecuritySchemeIn.HEADER,
        scheme = "bearer",
        flows = @OAuthFlows(authorizationCode = @OAuthFlow(
                authorizationUrl = "${springdoc.oAuthFlow.authorizationUrl}"
                , tokenUrl = "${springdoc.oAuthFlow.tokenUrl}", scopes = {
                @OAuthScope(name = "openid"),
                @OAuthScope(name = "email"),
                @OAuthScope(name = "profile"),
        })))
@Configuration
public class OpenApiConfig {
}
````

```yaml
springdoc:
  show-login-endpoint: true
  swagger-ui:
    oauth:
      clientId: xxxx
      use-pkce-with-authorization-code-grant: true
  oAuthFlow:
    authorizationUrl: http://localhost:8080/oauth/v2/authorize
    tokenUrl: http://localhost:8080/oauth/v2/token
```
